version: "3.9"

services:
  api:
    build: ./apps/api
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      UPSTASH_REDIS_REST_URL: ${UPSTASH_REDIS_REST_URL}
      UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRES_IN: ${REFRESH_TOKEN_EXPIRES_IN:-7d}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS:-12}
      CORS_ORIGIN: ${CORS_ORIGIN}
      ENABLE_SWAGGER: ${ENABLE_SWAGGER:-false}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  web:
    build: ./apps/web
    environment:
      NODE_ENV: production
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000/api/v1}
    ports:
      - "3001:3000"
    depends_on:
      - api

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fresh_shop_api
      POSTGRES_USER: fresh_shop_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
